#include <iostream> 
#include <string> 
#include <map> 
#include <mountain.cpp> 


using namespace std;

//PLAYER CHOOSES TO MOVE FORWARD, PLAY CARD OR STAY PUT
//AS PLAYER MOVES FORWARD, THEY ENCOUNTER CAMPS. CAN CHOOSE 
//TO STAY AT CAMPS OR MOVE PAST THEM
//AFTER PLAYER CHOICE, MOUNTAIN PLAYS CARD
//MOUNTAIN CARDS CAN KILL OR OTHERWISE DISRUPT PLAYER

//PLAYER GOAL: GET TO SUMMIT AND COME DOWN
//MOUNTAIN GOAL: KILL PLAYER



int main() { 



    return 0;   

}